#!/bin/sh

echo "mysql://$DBUSER:$DBPASS@$DBHOST/sonar"

sed -i "s/^sonar.jdbc.url=jdbc:h2:/#sonar.jdbc.url=jdbc:h2:/g" \
    /usr/local/share/sonarqube/conf/sonar.properties
sed -i "s/^#sonar.jdbc.url=jdbc:mysql:\/\/\(.*\):3306/sonar.jdbc.url=jdbc:mysql:\/\/$DBHOST:$DBPORT/g" \
    /usr/local/share/sonarqube/conf/sonar.properties
sed -i "s/^sonar.jdbc.username=sonar/sonar.jdbc.username=$DBUSER/g" \
    /usr/local/share/sonarqube/conf/sonar.properties && \
sed -i "s/^sonar.jdbc.password=sonar/sonar.jdbc.password=$DBPASS/g" \
    /usr/local/share/sonarqube/conf/sonar.properties

printf "SET GLOBAL binlog_format = 'MIXED';\nCREATE DATABASE IF NOT EXISTS sonar DEFAULT CHARACTER SET 'utf8';\n" | mysql -u $DBUSER -p$DBPASS -h $DBHOST -P $DBPORT

/usr/local/share/sonarqube/bin/linux-x86-64/sonar.sh console